version: '2'

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16

services:

  docker_proxy:
    image: nginx
    container_name: docker_proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "90:80"
    networks:
      default:
        ipv4_address: 172.33.2.1


  test_ui:
    image: nginx:1.13.0-alpine
    container_name: test_ui
    volumes:
      - ./test-app/dist/test-app/:/var/www/html/website
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4200:80
    networks:
      default:
        ipv4_address: 172.33.1.1	


  node-express:
    # build: ../EX_MVC/
    image: best_api:test
    container_name: best_api
    command: npm run startAPI
    ports:
      - 9001:9001
     networks:
      default:
        ipv4_address: 172.33.1.2
